### ISSUE TITLE
auth command raises error

### ISSUE THREAD

**Issue by mb6ockatf** [Zerogoki00/vk-audio-downloader#3]
Reproduce with `./vkaudio.py auth <login> <password>`
error:
```python
Traceback (most recent call last):
  File "/home/mb6ockatf/projects/vk-audio-downloader/./vkaudio.py", line 25, in <module>
    vk = VkAPI(login=username, password=password)
  File "/home/mb6ockatf/projects/vk-audio-downloader/utils/vkapi.py", line 42, in __init__
    self.try_auth(login, password)
  File "/home/mb6ockatf/projects/vk-audio-downloader/utils/vkapi.py", line 63, in try_auth
    raise VkAuthError(resp["error"])
utils.vkapi.VkAuthError: invalid_client
```

System:
```sh
$ uname -a
Linux archlinux 6.1.20-1-lts
```

**Comment by Zerogoki00** [comment]
This project is outdated (API has changed) and I currently have no time to maintain it. Maybe I'll fix it later

**Comment by mb6ockatf** [comment]
ok. i will close this issue for now

that's so bad of them not to keep backwards compatibility
